config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  get '/search_movies', to: 'movies#search_movies'

  resources :movies, only: [:index, :show] do
    resources :recommendations, only: [:create]
    resources :bookmarks, only: [:create]

  end

  resources :tags, only: [:destroy]

  resources :bookmarks, only: [:destroy, :index]

  resources :recommendations, only: [:destroy, :index] do
    resources :tags, except: :destroy
  end


  resources :users, only: [:show, :index, :edit] do
    member do
      get "follow", to: "users#follow"
      patch "unfollow", to: "users#unfollow"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :recommendations, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  has_many :tags, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :recommendation

  include PgSearch::Model
  pg_search_scope :search_by_tag_name,
    against: [ :name ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recommendations, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_one_attached :photo
  acts_as_followable
  acts_as_follower

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include PgSearch::Model
  pg_search_scope :search_by_first_name_and_last_name,
    against: [:first_name, :last_name],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :photo, :bio])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @movie = Movie.find(params[:movie_id])
    @bookmark = Bookmark.new
    @page = params[:page]
    @bookmark.movie = @movie
    @bookmark.user = current_user
    if @bookmark.save
      respond_to do |format|
        format.html { redirect_to user_path(current_user)}
        format.js
      end
    else
      render "movies#index"
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.destroy
      respond_to do |format|
        format.html { redirect_to user_path(current_user)}
        format.js
      end
    end
  end

  def index
    @bookmarks = Bookmark.all
    @bookmarks = current_user.bookmarks
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # def bookmarked
  #   @movies = Movie.where
  # end

  def index
    if params[:query].present?
      @movies = Movie.where("title ILIKE ?", "%#{params[:query]}%")
    else
      @movies = Movie.all
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def search_movies
    # if params[:input].present?
    @search_movies = Movie.where("title ILIKE ?", "%#{params[:input]}%")
    @query = params[:input]
    respond_to do |format|
      format.js
    end
  end

  def movie_params
    params.require(:movie).permit(:title, :description, :genre, :year)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    if params[:query].present?
      @movies = Movie.search_by_title_and_location(params[:query]).first(4)
    else
      @movies = Movie.first(5)
    end
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  def index
    @recommendations = current_user.all_follows.map do |follower|
      follower.followable.recommendations
    end
      # recommendation.all.order("created_at desc")
    @recommendations = @recommendations.flatten
  end

  def create
    # raise
    @recommendation = Recommendation.new()
    @recommendation.user = current_user
    @movie = Movie.find(params[:movie_id])
    @recommendation.movie = @movie

    if @recommendation.save
       respond_to do |format|
        format.html { redirect_to user_path(current_user)}
        format.js
      end
    else
      render "movies/index"
    end
  end

    def destroy
      @recommendation = Recommendation.find(params[:id])
      if @recommendation.destroy
        respond_to do |format|
        format.html { redirect_to user_path(current_user)}
        format.js
        end
      end
    end

    def show
      @tag = Tag.new
    end

  # def recommedations_params
  #   params.require(:recommendation).permit(:)
  # end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
    @tag = Tag.new
    @recommendation = Recommendation.find(params[:recommendation_id])
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def create
    @tag = Tag.new(strong_params)
    @recommendation = Recommendation.find(params[:recommendation_id])
    @tag.recommendation_id = @recommendation.id
    if @tag.save
        respond_to do |format|
        format.html { redirect_to user_path(current_user)}
        format.js  # <-- will render `app/views/tags/create.js.erb`
      end
    else
        respond_to do |format|
        format.html { render 'new/tag' }
        format.js  # <-- idem
      end
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    if @tag.destroy
     respond_to do |format|
        format.html { redirect_to user_path(current_user)}
        format.js  # <-- will render `app/views/tags/create.js.erb`
      end
    end
  end



private



  def strong_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:query].present?
      @users = User.all.search_by_first_name_and_last_name(params[:query])
    else
      @users = User.all
    end
  end

  def show
    @user = User.find(params[:id])
    @tag = Tag.new
    if params[:query].present?
      sql_query = "tags.name @@ :query"
      @recommendations = Recommendation.joins(:tags).where(sql_query, query: "%#{params[:query]}%")
      @recommendations = @recommendations.select { |r| r.user == @user }
    else
      @recommendations = @user.recommendations
    end
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow(@user)
    redirect_to user_path(@user)
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.stop_following(@user)
    redirect_to user_path(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookmarks/destroy.js.erb
document.querySelector('.card_<%= @bookmark.id %>').remove();

app/views/bookmarks/index.html.erb
<h1>Bookmarked</h1>

<% @bookmarks.each do |bookmark| %>

<div class="card-product-profile">
     <img src="<%= bookmark.movie.picture_url %>" />
     <div class="card-product-infos-profile">
       <h2 ><%= bookmark.movie.title %></h2>
       <p><%= bookmark.movie.description %></p>
       <p><%= bookmark.movie.genre %></p>
       <p><%= bookmark.movie.year %></p>
       <p class="Movie_icone"> IMDB NETFLIX AMAZON PRIME</p>
       <%= link_to "Delete", bookmark_path(bookmark), method: :delete, data: {confirm: "Whatt Why?"}%>
       </div>
   </div>
<% end %>

app/views/movies/_card.html.erb
<div class="card-product-profile">
  <img src="<%= recommendation.movie.picture_url%> "/>
  <div class="card-product-infos-profile">
    <h2 ><%= recommendation.movie.title %></h2>
    <p><%= recommendation.movie.description %></p>
    <%= link_to 'Add a tag', new_recommendation_tag_path(recommendation), class: "btn btn-primary" %>
    <button>Delete movie</button>
    <p><%= @user.first_name %> has recommended this movie with the tags:</p>
    <% recommendation.tags.each do |tag| %>
      <p class='tag'><%= tag.name %></p>
    <% end %>
    <div class="where-to-watch">
      <% if recommendation.movie.imdb_url.present? %>
        <%= link_to recommendation.movie.imdb_url, target: "_blank" do %>
          <li><i class="fab fa-imdb"></i></li>
        <% end %>
      <% end %>
      <% if recommendation.movie.netflix_url.present? %>
        <%= link_to recommendation.movie.netflix_url, target: "_blank" do %>
        <li><img src="https://www.freepnglogos.com/uploads/netflix-logo-circle-png-5.png" alt="netflix" style="width:15px; height:15px;"></li>
        <% end %>
      <% end %>
      <% if recommendation.movie.amazon_url.present? %>
        <%= link_to recommendation.movie.amazon_url, target: "_blank" do %>
        <li><i class="fab fa-amazon"></i></li>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container pt-4">
  <div class="lets-go mb-4">
    <div class="lets-go-info d-flex flex-column align-items-center" >
      <h3 style="min-width: 36vw;">
        <span id="banner-typed-text"></span>
      </h3>
      <%= link_to recommendations_path  :action => 'go' do %>
        <!-- <div class="lets-go-button">Let's Go</div> -->
        <div class="my-div">
          <button class="learn-more"><span>Let's go</span></button>
        </div>
      <% end %>
    </div>
    <%= cl_image_tag "https://res.cloudinary.com/dtjblav7i/image/upload/v1574955096/illustrations_f9yo5s.svg", class:'lets-go-picture' %>
  </div>
  <h4 class="recommended-title">Most recommended movies this month</h4>
  <div class="line-seporater"></div>
  <div class="carousel">
    <% @movies.each do |movie| %>
      <%= image_tag movie.picture_url, class:'movie-picture', data: { toggle: 'modal', target: '#modal' + movie.id.to_s} %>
    <% end %>
  </div>
</div>
<!-- modal -->
<% @movies.each do |movie| %>
  <div class="modal fade" id="modal<%= movie.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog " role="document">
      <div class="modal-content info-modal">
        <div class="modal-header modal-head">
          <h5 class="modal-title title-modal" id="exampleModalLabel"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <h2><%= movie.title %> - <em><%= movie.year %></em></h2>
          <p><%= movie.storyline %></p>


          <div class="d-flex">

          <a class="imdb mr-4" href="https://www.imdb.com/title/tt0095765/?ref_=fn_al_tt_1"><img src="https://res.cloudinary.com/dtjblav7i/image/upload/v1575290384/imdb_fkuqhx.jpg" style='width:50px'></a>
          <a class="netflix" href="https://www.netflix.com/search?q=incep&jbv=70131314&jbp=0&jbr=0"><img src="https://res.cloudinary.com/dtjblav7i/image/upload/v1575290264/netflliw_fwehh5.png" style='width:80px'></a>
          <a class="amazon mr-1" href="https://www.amazon.co.uk/Aliens-Lan/dp/B00HNJSU1W/ref=sr_1_1?keywords=aliens&qid=1575294742&s=instant-video&sr=1-1"><img src="https://res.cloudinary.com/dtjblav7i/image/upload/v1575290073/amazon_logo_ffi0fs.png" style='width:100px'></a>
        </div>

        </div>
        <div class="modal-footer footer-modal">
        </div>
        <div class="modal-footer footer-modal d-flex align-items-center">
          <span class="modal-reco d-flex align-items-center justify-content-center" id="recommendbutton-<%= movie.id%>">
            <% if Recommendation.find_by(movie: movie, user: current_user) %>
              <span >Recommended</span>
            <% else %>
              <%= link_to "Recommend", movie_recommendations_path(movie), method: :post, :remote => true %></span>
          <% end %>
        </span>
        <% if Bookmark.find_by(movie: movie, user: current_user) %>
          <span class="modal-reco ">Bookmarked</span>
        <% else %>
          <%= link_to movie_bookmarks_path(movie, page: "home"), method: :post, remote: true do %>
            <span class="modal-reco" id="movie-<%= movie.id %>">Bookmark</span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>
<!-- Modal -->
<% if !user_signed_in? %>
  <div class="home-sign-up-box">
    <%= simple_form_for(registration_path(User.new)) do |f| %>
      <%= f.error_notification %>
      <div class="home-form-inputs">
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :email,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "email" }%>
        <%= f.input :password,
                    required: true,
                    hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                    input_html: { autocomplete: "new-password" } %>
        <%= f.input :password_confirmation,
                      required: true,
                      input_html: { autocomplete: "new-password" } %>
      </div>
      <div class="lets-go-submit">
        <%= f.button :submit, "Sign up" %>
      </div>
    <% end %>
  </div>
<% end %>
<div class="three-box-container">
  <%= cl_image_tag "https://res.cloudinary.com/dtjblav7i/image/upload/v1575028623/background_fyixao.svg" %>
  <h1>Bookmark</h1>
  <h2>Millions of recommendations from your friends and others</h2>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%#= image_tag src="https://res.cloudinary.com/dtjblav7i/image/upload/v1575369158/bookmark_new_size_edit_jo7nsq.png", width: 800 %>
    <%= image_tag 'new-bookmark-logo.png', width: 800 %>
  <% end %>
  <!-- <div class ="buttons d-flex justify-content-around" > -->

  <div class="d-flex align-items-center">

    <div class="searchbar">
      <%= form_tag users_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query], autocomplete: 'off',
          class: "form-control",
          placeholder: "Find a friend"%>
      <% end %>
    </div>
    <%= link_to 'Movies', movies_path,class: "nav-link" %>
    <%= link_to 'Whats Up', recommendations_path,class: "nav-link" %>
    <!-- </div> -->

    <% if user_signed_in? %>
      <%= link_to "My Profile", user_path(current_user.id), class: "nav-link" %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>

    <% else %>
      <%= link_to "Login", new_user_session_path, class: "nav-link" %>

    <% end %>
  </div>

</div>

app/views/users/index.html.erb
<% unless params[:query].present? %>
<% end %>
<% if params[:query].present? %>
  <h1 style="margin-left:74px";>Theses are the search results for "<%= params[:query]%>"</h1>
<% end %>
<br>
<br>
<div class="container">
  <% @users.each do |user| %>
    <div class="friend-card d-flex ">
      <div class="friend-card-avatar">
        <% if user.photo.attached? %>
          <%= cl_image_tag user.photo.key %>
        <% else %>
          <!-- <img src="https://pixy.org/download/301929/" class="friend-card-avatar"> -->
          <%= image_tag "https://pixy.org/download/301929/",  height: 100, width: 100, crop: :fill, class: 'friend-card-avatar'  %>
        <% end %>
      </div>
      <% if current_user.following?(user) %>
        <%= link_to unfollow_user_path(user), method: :patch do %>
          <i class="fas fa-minus icon"></i>
        <% end %>
      <% elsif user == current_user %>
        <div class="linktoedit">
          <%= link_to 'Edit Profile', edit_user_registration_path %>
        </div>
      <% else %>
        <%= link_to follow_user_path(user) do %>
          <i class="fas fa-plus icon"></i>
        <% end %>
      <% end %>
      <div class="friend-information d-flex flex-column">
        <%= link_to user_path(user) do %>
          <h1><%= user.first_name&.capitalize %> <%= user.last_name&.capitalize %> </h1>
        <% end %>
        <!-- <p>Bio: is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout</p> -->
        <% if user.bio %>
          <p><%= user.bio.truncate(100) %></p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<br>
<br>
<br>
<br>
<br>

app/views/users/show.html.erb
<!--Profile card-->
<div id="container_master_my_profile">
  <!-- profile card -->
  <div id="container_profile_card_my_profile">
    <div id="text_profile_card">
      <p id="profile_name"><strong><%= @user.first_name %> <%= @user.last_name %></strong></p>
      <% if @user.bio.present? %>
        <p id="profile_bio"><%= @user.bio.truncate(100) %></p>
      <% end %>
      <div class="social">
        <p class="d-inline">Followers <strong><%= @user.followers_by_type_count('User') %></strong></p>
        <p class="d-inline">Following <strong><%= @user.all_follows.length %></strong>
        </div>
        <div id="follow_or_not">
          <% unless @user == current_user %>
            <% if current_user.following?(@user) %>
              <%= link_to unfollow_user_path(@user), method: :patch do %>
                <button id="follow" class="btn btn-primary">Unfollow</button>
              <% end %>
            <% else %>
              <%= link_to follow_user_path(@user) do %>
                <button id="follow" class="btn btn-light">Follow</button>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <div id='edit_profile_button_new'>
          <% if @user == current_user %>
            <%= link_to edit_user_registration_path do %>
              <button type="button" class="btn btn-dark">Edit Profile</button>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div id="white_background">
    </div>
    <div id="avatar_profile">
      <% if @user.photo.attached? %>
        <%= cl_image_tag @user.photo.key, height: 100, width: 100, crop: :fill %>
      <% else %>
        <%= image_tag "https://pixy.org/download/301929/",  height: 100, width: 100, crop: :fill  %>
      <% end %>
    </div>
    <!--/Profile card-->
    <!--Buttons tab-->
    <div class="container_reco">
      <!--/Buttons tab-->
      <!-- /profile card -->
      <!-- tab -->
      <div id='container_tabs'>
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Recommendations</a>
          </li>
          <% if @user == current_user %>
            <li class="nav-item">
              <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Bookmarks</a>
            </li>
          <% end %>
        </ul>
      </div>
      <!-- /tab -->
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
          <!-- Linebreak -->
          <!-- Search Bar -->
          <div id='container_search_border'>
            <div id='search_profile'>
              <% if @user == current_user %>
                <%= form_tag movies_path, method: :get do %>
                  <%= text_field_tag :query,
                params[:query], autocomplete: 'off', class: "form-control movielistid",
                placeholder: "Search for a movie to recommend"%>
                <% end %>
                <div id="suggestions"></div>
              <% else %>
                <%= form_tag user_path(@user), method: :get do %>
                  <%= text_field_tag :query, params[:query], autocomplete: 'off', class: "form-control",
                placeholder: "search for a tag"%>
                <% end %>
              <% end %>
            </div>
          </div>
          <!-- /Search Bar -->
          <!-- Recos -->
          <% @recommendations.each do |recommendation| %>
            <div class="card-product-profile card_<%= recommendation.id %>">
            <img src="<%= recommendation.movie.picture_url%> "/>
            <div class="card-product-infos-profile">
              <h2 id='movie-title-profile' ><%= recommendation.movie.title %></h2>
              <p><%= recommendation.movie.storyline %></p>
              <% if @user == current_user %>
                <button type="button" id='add_a_tag' data-toggle="modal" data-target="#addTagModal_<%= recommendation.id %>">
                  Add a new tag
                </button>
                <div class="modal fade" id="addTagModal_<%= recommendation.id %>" tabindex="-1" role="dialog" aria-labelledby="addTagModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header tag-header">
                          <h5 class="modal-title tag-title">Create a tag</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body tag-body">
                          <%= simple_form_for([recommendation, @tag], remote: true) do |f| %>
                            <%= f.input :name %>
                        </div>
                        <div class="modal-footer tag-footer">
                          <button class="btn btn-secondary tag-btn">Create a tag</button>
                          <button type="button" class="btn btn-secondary tag-btn" data-dismiss="modal">Close</button>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
              <% end %>
              <div class='d-flex tags_<%= recommendation.id %>'>
                <% recommendation.tags.each do |tag| %>
                  <% if @user == current_user %>
                    <div class='tag_<%= tag.id %>'>
                      <div class='tag'>
                        <%= tag.name %>
                      </div>
                        <% if tag.name.present? %>
                          <p class='text-center'id='remove-tage-icone'><strong><%= link_to " x ", tag_path(tag), method: :delete, remote: true, data: {confirm: "Are you sure you want to delete this tag?"}%></strong></p>
                        <% end %>
                    </div>
                  <% else %>
                   <div class='tag'><%= tag.name %></div>
                    <% if tag.name.present? %>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
              <div id="bookmark-from-friends">
                  <% if @user != current_user && !current_user.bookmarks.where(movie: recommendation.movie).any? %>
                    <%= link_to ' Bookmark', movie_bookmarks_path(recommendation.movie), method: :post, :remote => true, class: "add-to-bookmarks" %>
                    <%= link_to ' Recommend', movie_recommendations_path(recommendation.movie), method: :post, :remote => true, class: "add-to-recommendations" %>
                  <% end %>
                </div>
              <!--
              <div class="where-to-watch">
                <% if recommendation.movie.imdb_url.present? %>
                  <%= link_to recommendation.movie.imdb_url, target: "_blank" do %>
                    <li><i class="fab fa-imdb"></i></li>
                  <% end %>
                <% end %>
                <% if recommendation.movie.netflix_url.present? %>
                  <%= link_to recommendation.movie.netflix_url, target: "_blank" do %>
                    <li><img src="https://www.freepnglogos.com/uploads/netflix-logo-circle-png-5.png" alt="netflix" style="width:15px; height:15px;"></li>
                  <% end %>
                <% end %>
                <% if recommendation.movie.amazon_url.present? %>
                  <%= link_to recommendation.movie.amazon_url, target: "_blank" do %>
                  <% end %>
                <% end %>
                -->
            </div>
            <div class="right-info">
              <% if @user == current_user %>
                <button id='add_a_tag_delete'><%= link_to "Delete recommendation", recommendation_path(recommendation), method: :delete, data: {confirm: "Are you sure? Do you want to delete this recommendation?"}, remote: true %></button>
              <% end %>
              <div id="links">
                <ul>
                  <li class="imdb"><a href="https://www.imdb.com/title/tt0095765/?ref_=fn_al_tt_1" target="_blank"><img src="https://res.cloudinary.com/dtjblav7i/image/upload/v1575290384/imdb_fkuqhx.jpg" style='width:50px'></a></li>
                  <li class="netflix"><a href="https://www.netflix.com/search?q=incep&jbv=70131314&jbp=0&jbr=0" target="_blank"><img src="https://res.cloudinary.com/dtjblav7i/image/upload/v1575290264/netflliw_fwehh5.png" style='width:80px'></a></li>
                  <li class="amazon"><a href="https://www.amazon.co.uk/Aliens-Lan/dp/B00HNJSU1W/ref=sr_1_1?keywords=aliens&qid=1575294742&s=instant-video&sr=1-1" target="_blank"><img src="https://res.cloudinary.com/dtjblav7i/image/upload/v1575290073/amazon_logo_ffi0fs.png" style='width:100px'></a></li>
                </ul>
              </div>
            </div>
          </div>
        <% end %>
      <!--/Recos-->
      </div><!-- /closing div master profile -->
<!--/Profile card-->
      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
<!-- Bookmarks-->
        <% @user.bookmarks.each do |bookmark| %>
          <div class="card-product-profile card_<%= bookmark.id %>">
            <img src="<%= bookmark.movie.picture_url%> "/>
                <div class="card-product-infos-profile">
                  <h2 ><%= bookmark.movie.title %></h2>
                  <p><%= bookmark.movie.storyline %></p>
                </div>
                <div id="right-info-bookmark">
                  <button id='add_a_tag_delete'><%= link_to "Delete this Bookmark", bookmark_path(bookmark), method: :delete, data: {confirm: "Whatt Why?"}, remote: true %></button>
                  <div id="links">
                    <ul>
                      <li class="imdb"><a href="https://www.imdb.com/title/tt0095765/?ref_=fn_al_tt_1"><img src="https://res.cloudinary.com/dtjblav7i/image/upload/v1575290384/imdb_fkuqhx.jpg" style='width:50px'></a></li>
                      <li class="netflix"><a href="https://www.netflix.com/search?q=incep&jbv=70131314&jbp=0&jbr=0"><img src="https://res.cloudinary.com/dtjblav7i/image/upload/v1575290264/netflliw_fwehh5.png" style='width:80px'></a></li>
                      <li class="amazon"><a href="https://www.amazon.co.uk/Aliens-Lan/dp/B00HNJSU1W/ref=sr_1_1?keywords=aliens&qid=1575294742&s=instant-video&sr=1-1"><img src="https://res.cloudinary.com/dtjblav7i/image/upload/v1575290073/amazon_logo_ffi0fs.png" style='width:100px'></a></li>
                    </ul>
                  </div>
                </div>
              </div>
            <% end %>
            <!--/Bookmarks-->
          </div>
          <!--NOTE: closing DIV Container - reco -->
        </div>
        <!--NOTE: closing DIV Container - profile -->
      </div>
    </div>
  <br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>